### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tonyamtar** [avenger11/HomeOS#2]
Bonjour,

J'ai vu que tu était Français dans les screenshot :)

Déjà vraiment félicitation car ton travail est vraiment magique !

Peux tu faire une petit tuto de quelques lignes pour expliquer comment utiliser ton thème ?

Merci à toi

**Comment by avenger11** [comment]
Salut, 

Merci :) 

La documentation avance mais est très préliminaire encore.
https://avenger11.github.io/HomeOS-doc/

**Comment by avenger11** [comment]
See previous comment
